### ISSUE TITLE
Doesn't work in Django 2.0

### ISSUE THREAD

**Issue by toxa23** [idlesign/django-siteprefs#15]
```  File "settings.py", line 240, in <module>
    from siteprefs.toolbox import patch_locals, register_prefs
  File "/lib/python3.6/site-packages/siteprefs/toolbox.py", line 6, in <module>
    from .models import Preference
  File "/lib/python3.6/site-packages/siteprefs/models.py", line 8, in <module>
    class Preference(models.Model):
  File "/lib/python3.6/site-packages/django/db/models/base.py", line 100, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/lib/python3.6/site-packages/django/apps/registry.py", line 244, in get_containing_app_config
    self.check_apps_ready()
  File "/lib/python3.6/site-packages/django/apps/registry.py", line 127, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.```

**Comment by idlesign** [comment]
Thank you for the report. I'll try to reproduced it this week.Meanwhile a full stacktrace would be helpful.14:40, 29 мая 2018 г., Anton Alekseev <notifications@github.com>:    from siteprefs.toolbox import patch_locals, register_prefs
  File "/lib/python3.6/site-packages/siteprefs/toolbox.py", line 6, in <module>
    from .models import Preference
  File "/lib/python3.6/site-packages/siteprefs/models.py", line 8, in <module>
    class Preference(models.Model):
  File "/lib/python3.6/site-packages/django/db/models/base.py", line 100, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/lib/python3.6/site-packages/django/apps/registry.py", line 244, in get_containing_app_config
    self.check_apps_ready()
  File "/lib/python3.6/site-packages/django/apps/registry.py", line 127, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.```

**Comment by toxa23** [comment]
Yes, the exception appears at the very beginning.
Please take a look at my settings.py and trace log. I do not deny, maybe this is me doing something wrong.
[sources.zip](https://github.com/idlesign/django-siteprefs/files/2054095/sources.zip)

**Comment by idlesign** [comment]
Some hints:

1. The basic idea with Django is to use app. So you need to create `settings.py` in your app (just as in quickstart) and define settings there. 
2. Boolean value is handled automatically, no need to define field.
3. To deal with env vars you can use https://github.com/idlesign/envbox or something similar instead of `get_env_variable`.

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.

**Comment by jayvdb** [comment]
I encountered this also, when I try to described preferences in my `project/settings.py`

```
Traceback (most recent call last):
  File "/path_to_root/project_wide/settings.py", line 788, in <module>
    from siteprefs.toolbox import preferences
  File "/usr/lib/python3.8/site-packages/siteprefs/toolbox.py", line 11, in <module>
    from .models import Preference
  File "/usr/lib/python3.8/site-packages/siteprefs/models.py", line 6, in <module>
    class Preference(models.Model):
  File "/usr/lib/python3.8/site-packages/django/db/models/base.py", line 107, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/usr/lib/python3.8/site-packages/django/apps/registry.py", line 252, in get_containing_app_config
    self.check_apps_ready()
  File "/usr/lib/python3.8/site-packages/django/apps/registry.py", line 135, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

@toxa23 's solution works for me https://github.com/BanzaiTokyo/askapp/blob/f1a5aba/siteprefs/toolbox.py#L24 .  I'll submit a patch shortly.
